### ISSUE TITLE
GLES2 probably not working in RPi3 AArch64?

### ISSUE THREAD

**Issue by btwael** [LdB-ECM/Raspberry-Pi#12]
So I just tried to run GLES2 example in a RPi3 with a [5inch HDMI touch Display-B](http://www.lcdwiki.com/5inch_HDMI_Display-B), when I included the example "kernel8.img" to the SD card I don't get the expected result, but when I use the "kernel7.img" (32bit) everything works fine.

So probably the GLES2 is not working with RPi3 AAch64?

P.S. when i put in the SD card both files "kernel7.img" and "kernel8.img" everything works fine!

**Comment by LdB-ECM** [comment]
You absolutely sure it's a Pi3 and not a Pi2 :-)

**Comment by btwael** [comment]
Just re-checked, everything works fine!

The problem comes from the initial outdated image I used to flash the SD card, which is probably configured to ignore the kernel8.

Thank you for your experiments, it really help to get into advanced bare metal, keep it up!
