### ISSUE TITLE
suggestion to avoid errors in mailboxes

### ISSUE THREAD

**Issue by eco747** [LdB-ECM/Raspberry-Pi#18]
in the _mailbox_tag_message_ function i suggest to use this message declaration instead of message[**32**]
this way if you pass more than 32 elements it will not crash...

uint32_t attribute((aligned(16))) message[**data_count**+3];

**Comment by LdB-ECM** [comment]
I like the idea and will do that but actually because it minimizes the stack use. The 32 entries was an improbably large size there isn't really that many tags you could clump together.
