### ISSUE TITLE
Possible to enable/disable UART without reboot?

### ISSUE THREAD

**Issue by theronic** [LdB-ECM/Raspberry-Pi#20]
I see there is a UARTEN memory register reference in [rpi-SmartStart.c](https://github.com/LdB-ECM/Raspberry-Pi/blob/master/10_virtualmemory/rpi-SmartStart.c#L546) as per page 187 of the BCM2835 Peripheral manual. I assume that flag corresponds to the `enable_uart=1` setting in /boot/config.txt.

Is it possible to enable/disable UART by twiddling those bits without rebooting, even from Raspbian? 

Any help is much appreciated.

**Comment by LdB-ECM** [comment]
It does a little more than that it stops raspbian attaching a console to it for kernel messages it is documented
https://www.raspberrypi.org/documentation/configuration/uart.md

Disabling the register would leave the console bound by the data going into hyperspace and not appearing anywhere but would waste CPU time.
