### ISSUE TITLE
GLES

### ISSUE THREAD

**Issue by mooseyfaith** [LdB-ECM/Raspberry-Pi#22]
Hi,

I can't display any of your GLES examples on my raspberry PI 3 B+ or PI 1 B+ V1.2 models.

It does display some text for the smartstartup, but then nothing. (neither the precompiled files nor the ones I compiled myself)
I would really love to make this work, you seem to have gotten pretty far with it.
Hope you can help me out, thanks for your work anyway!

**Comment by LdB-ECM** [comment]
If you are getting the smartstart text then it should work seamlessly ... try just downloading up todate firmware for the Pi

https://github.com/raspberrypi/firmware/tree/master/boot
start.elf, bootcode.bin and fixup.dat from there onto your SD card please

**Comment by mooseyfaith** [comment]
I did as you said an it works fine now.
Thank you very much for your quick help and thank you for this awsome code!
