### ISSUE TITLE
Bulid issue when using make

### ISSUE THREAD

**Issue by eunwoo** [LdB-ECM/Raspberry-Pi#23]
Hello,

I posted an issue a gew month ago. But the problem is not solved yet. I set up the same build environment which includes gnu compiler and make. When executing make Pi3-64, I have got errors. Is there any suggestion?

**Comment by LdB-ECM** [comment]
I am looking at your posts your issues were about an LCD.
The only compiling issue you mentioned was a few warnings about anonymous structs.

Which example can't you build and what is the error?

**Comment by eunwoo** [comment]
The result is as follows. 
https://github.com/eunwoo/rpi3/blob/master/compile_error.jpg

The Makefile is as follows. The contents is the same as yours except the path which points to the compiler that I installed on my computer.

```
# If cross compiling from windows use native GNU-Make 4.2.1
# https://sourceforge.net/projects/ezwinports/files/
# download "make-4.2.1-without-guile-w32-bin.zip" and set it on the enviroment path
# There is no need to install cygwin or any of that sort of rubbish

ifeq ($(OS), Windows_NT)
	#WINDOWS USE THESE DEFINITIONS
	RM = -del /q /f
	SLASH = \\
	SWALLOW_OUTPUT = >nul 2>nul
else
	#LINUX USE THESE DEFINITIONS
	RM = -rm -f
	SLASH = /
	SWALLOW_OUTPUT =
endif 


Pi3-64: CFLAGS = -Wall -O3 -mcpu=cortex-a53+fp+simd -ffreestanding -nostartfiles -std=c11 -mstrict-align -fno-tree-loop-vectorize -fno-tree-slp-vectorize -Wno-nonnull-compare
Pi3-64: ARMGNU = d:/pi/gcc_linaro_7_1/bin/aarch64-elf
Pi3-64: LINKERFILE = rpi64.ld
Pi3-64:	SMARTSTART = SmartStart64.S
Pi3-64: IMGFILE = kernel8.img

Pi3: CFLAGS = -Wall -O3 -mcpu=cortex-a53 -mfpu=neon -mfloat-abi=hard -ffreestanding -nostartfiles -std=c11 -mno-unaligned-access -fno-tree-loop-vectorize -fno-tree-slp-vectorize -Wno-nonnull-compare
Pi3: ARMGNU = D:/gcc-arm-none-eabi-7/bin/arm-none-eabi
Pi3: LINKERFILE = rpi32.ld
Pi3: SMARTSTART = SmartStart32.S
Pi3: IMGFILE = kernel8-32.img

Pi2: CFLAGS = -Wall -O3 -mcpu=cortex-a7 -mfpu=neon -mfloat-abi=hard -ffreestanding -nostartfiles -std=c11 -mno-unaligned-access -fno-tree-loop-vectorize -fno-tree-slp-vectorize -Wno-nonnull-compare
Pi2: ARMGNU = D:/gcc-arm-none-eabi-7/bin/arm-none-eabi
Pi2: LINKERFILE = rpi32.ld
Pi2: SMARTSTART = SmartStart32.S
Pi2: IMGFILE = kernel7.img

Pi1: CFLAGS = -Wall -O3 -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -ffreestanding -nostartfiles -std=c11 -mno-unaligned-access -fno-tree-loop-vectorize -fno-tree-slp-vectorize -Wno-nonnull-compare
Pi1: ARMGNU = D:/gcc-arm-none-eabi-7/bin/arm-none-eabi
Pi1: LINKERFILE = rpi32.ld
Pi1: SMARTSTART = SmartStart32.S
Pi1: IMGFILE = kernel.img

# The directory in which source files are stored.
SOURCE = ${CURDIR}
BUILD = build


# The name of the assembler listing file to generate.
LIST = kernel.list

# The name of the map file to generate.
MAP = kernel.map

# The names of all object files that must be generated. Deduced from the 
# assembly code files in source.

ASMOBJS = $(SOURCE)/$(SMARTSTART)
COBJS = $(patsubst $(SOURCE)/%.c,$(BUILD)/%.o,$(wildcard $(SOURCE)/*.c))


Pi3-64: kernel.elf
BINARY = $(IMGFILE)
.PHONY: Pi3-64

Pi3: kernel.elf
BINARY = $(IMGFILE)
.PHONY: Pi3

Pi2: kernel.elf
BINARY = $(IMGFILE)
.PHONY: Pi2

Pi1: kernel.elf
BINARY = $(IMGFILE)
.PHONY: Pi1

$(BUILD)/%.o: $(SOURCE)/%.s
	$(ARMGNU)-gcc -MMD -MP -g $(CFLAGS) -c  $< -o $@ -lc -lm -lgcc

$(BUILD)/%.o: $(SOURCE)/%.S
	$(ARMGNU)-gcc -MMD -MP -g $(CFLAGS) -c  $< -o $@ -lc -lm -lgcc

$(BUILD)/%.o: $(SOURCE)/%.c
	$(ARMGNU)-gcc -MMD -MP -g $(CFLAGS) -c  $< -o $@ -lc -lm -lgcc

kernel.elf: $(ASMOBJS) $(COBJS) 
	$(ARMGNU)-gcc $(CFLAGS) $(ASMOBJS) $(COBJS) -T $(LINKERFILE) -o kernel.elf -lc -lm -lgcc
	$(ARMGNU)-objdump -d kernel.elf > $(LIST)
	$(ARMGNU)-objcopy kernel.elf -O binary DiskImg/$(BINARY)
	$(ARMGNU)-nm -n kernel.elf > $(MAP)

# Control silent mode  .... we want silent in clean
.SILENT: clean

# cleanup temp files
clean:
	$(RM) $(MAP) 
	$(RM) kernel.elf 
	$(RM) $(LIST) 
	$(RM) $(BUILD)$(SLASH)*.o 
	$(RM) $(BUILD)$(SLASH)*.d 
	echo CLEAN COMPLETED
.PHONY: clean

```

**Comment by LdB-ECM** [comment]
I have exact same make and same GCC as you.
 
You are going to have to explain those strange looking directory slashes or lack thereof
This is my repeats of your exact commands
https://github.com/LdB-ECM/Docs_and_Images/blob/master/Images/screencap.jpg

The only difference I can see is the directory slash display. 
I will also add an all target to the makefile

Can you try "make all" with the new makefile in Arm32_64_USB

**Comment by eunwoo** [comment]
I tested with the file that you made.
https://github.com/LdB-ECM/Exchange/blob/master/Makefile
This is the result. It has no problem and I downloaded the kermel8.img and it works.
https://github.com/eunwoo/rpi3/blob/master/compile_error_new_make2.jpg

I live in South Korea, and the Windows 10 for Korean language displays backslash('\') as ￦. ￦ is normally used as a symbol of the unit of Korean money(pronounced 'WON'). In the command window, when I type backslash '\', ￦ characters is shown. I don't understand why this difference makes the error.

I changed build to Build, but the error happens as the same.  And I changed the first character of the folder name(Build -> build), but it is in vain. 

Is it necessary that I inspect the source code of make utility?

**Comment by LdB-ECM** [comment]
Did you try the makefile without target ... I am trying to understand what the issue with make is to look at the source myself.

On windows 10 you can install 2 languages if you just install english and run it for the command prompt that may also help. As a property  on a app you can select that apps to run a particular language. You can also global change it for short periods on the icon bar down on the bottom right next to time and date.

**Comment by eunwoo** [comment]
Normal slash '/' is also printed in '/', but backslash '\' is printed in Korean won '￦'.

And I changed the region in the settings, but the result is the same. Please see the screenshot below.
https://github.com/eunwoo/rpi3/blob/master/compile_error_english_region.jpg

**Comment by LdB-ECM** [comment]
Does that say ernel.elf or kernel.elf and what is with the comma ????

**Comment by LdB-ECM** [comment]
Oh the other thing .. see this line in the makefile
SOURCE = ${CURDIR}

That retrieves the current directory which is the thing it seems to be botching .. try manually setting it to your huge directory 
SOURCE =D;/Prog/Raspberry/Raspberry-Pi-master/Raspeberry-Pi-master/ARM32_64_USB/

**Comment by LdB-ECM** [comment]
Woah I installed korean and I think I found it ... there is a unicode funny character in the line
Pi3-64: SMARTSTART = SmartStart64.S
It is between the : S ... try deleting and retyping

When I am in Korean it looks like this

> Pi3-64: LINKERFILE = rpi64.ld
> Pi3-64:	SMARTSTART = SmartStart64.S
> Pi3-64: IMGFILE = kernel8.img

**Comment by eunwoo** [comment]
I tried the Makefile that you mentioned. Please see the first part of the post.
https://github.com/LdB-ECM/Raspberry-Pi/issues/23#issuecomment-488278072
And I also tried the Makefile in the post.
https://github.com/LdB-ECM/Raspberry-Pi/issues/23#issuecomment-488336354
The compile process went through smoothly without any problem.

And I did some test and I found the cause.
I changeded the original Makefile which includes strange character in 'Pi3-64: SMARTSTART = SmartStart64.S' as follows.
original: ASMOBJS = $(SOURCE)/$(SMARTSTART)
replaced: ASMOBJS = $(patsubst $(SOURCE)/%.S,$(BUILD)/%.o,$(SMARTSTART))
The strange unicode has no effect to the result.

**Comment by LdB-ECM** [comment]
Sorry I missed that earlier.

So if I change all the makefiles with that change you should be good to be able to compile now?

**Comment by eunwoo** [comment]
Thank you for helping with me compiling.

I did the test as you said. This table shows the result, I didn't test img file yet. 
'different path' means the compiler path is not the same as in 10_virtualmemory. 
But after fixing the compiler path, all the examples can be built without any problem except SimpleSched which only supports Pi3(32bit) not Pi3-64.

folder | result(compiling with Makefile/Screen) |  
-- | -- | --
10_virtualmemory | O |  
Arm32_64_USB | O |  
Core3Interrupt | O |  
FreeRTOSv10.1.1 | O | different path
GL_GUI_STEP1 | O |  
GLES2 | O |  
GLES2_Model | O |  
GLES2_Rotate | △ | Pi3-64.bat, different path
Multicore | △| Pi3-64.bat, different path
myBlinker | △ | Build folder is added   rpi-SmartStart.c, rpi_smartstart.h,   emb-stdio.c, emb-stdio.h is different from those of Core3Interrupt
PlayGround | △ | different path
RayCast | △ | Pi3-64.bat, different path,   Pi.bat instead of Pi3-32.bat
SD_FAT32 | △ | Pi3-64.bat, different path
SimpleSched | X |  

This is error message when compiling SimpleSched. I'm not good at analyzing Makefile, I have no idea why this error is made. I have used 32-bit compiler.
D:\Prog\Raspberry\Raspberry-Pi-master\Raspberry-Pi-master_Makefile\SimpleSched>make Pi3
D:\gcc-arm-none-eabi-7\bin\arm-none-eabi-gcc -Wall -O3 -march=armv8-a -mfpu=neon-vfpv4 -mfloat-abi=hard -mtune=cortex-a53 -mno-unaligned-access -fno-tree-loop-vectorize -fno-tree-slp-vectorize -Wno-nonnull-compare -nostdlib -nodefaultlibs -nostartfiles -ffreestanding -fno-asynchronous-unwind-tables -fomit-frame-pointer -c rpi-SmartStart.c -o build/rpi-SmartStart.o
arm-none-eabi-gcc: error: CreateProcess: No such file or directory
make: *** [Makefile:81: build/rpi-SmartStart.o] Error 1

**Comment by LdB-ECM** [comment]
Cheers for that will fix all that up tonight

**Comment by LdB-ECM** [comment]
Makefiles should all be working now, new version to allow Pi4 operation is being added so I will close this issue for now
