### ISSUE TITLE
Adding debug information to ELF

### ISSUE THREAD

**Issue by szoshi** [LdB-ECM/Raspberry-Pi#24]
Hello LdB,

I am trying to debug your project with an IDE and cannot do any HLL or ASM debugging as the debug information is excluded from the ELF file. I was able to find out that the DISCARD section at the bottom of the linker file does the trick. If I comment it out though, the file consists of a lot of unnecessary sections as well. 

Since I have no experience with linker scripts, would it be possible to modify the linker file to include debug sections as well? I am guessing it won't mess around with the final kernel images for most users and so should be harmless :|

I am currently debugging the USB example and am seeing some problems with the WFE, SEV mechanism. Being able to see the asm source code via debug is a bit more productive taht going through a lot of hex opcodes 

Thanks for all your efforts!

Szoshi

**Comment by szoshi** [comment]
Hi again,
please close this issue. I figured out the linker script changes to get my IDE to recognize just the debug inofrmation and ignore the other sections by adding their names in the discard part of the script.

**Comment by LdB-ECM** [comment]
Good work will close issue
