### ISSUE TITLE
None of the Kernel8 img  working on Raspberry Pi3

### ISSUE THREAD

**Issue by btauro** [LdB-ECM/Raspberry-Pi#5]
My SD card includes config bootcode start.bin kernel8.img.
The Part3 Tutorial worked but None of the codes in this repository have worked on my Pi3 yet.
A blank screen shows up when the raspberry pi3 is turned on,

**Comment by LdB-ECM** [comment]
Yes there was a bug with screen resolution in AARCH64 which has been resolved
