### ISSUE TITLE
Can't detect RPi Zero W in SmartStart32

### ISSUE THREAD

**Issue by boochow** [LdB-ECM/Raspberry-Pi#6]
Hi,
I tried to run your examples on my RPi-Zero W but they didn't work.
Since RPi Zero W uses GPIO for uart0 for communicating BT chip, Zero W is considered as not a RPi1 family in SmartStart32.S.
I have no idea how to detect Zero W correctly, so this is just a FYI.

**Comment by LdB-ECM** [comment]
It doesn't have the hardware I autodetect .. hmm I might change what I looking for need to go see what is common to all models.
