### ISSUE TITLE
"Could not transfer DATA to device" on calling HIDReadReport

### ISSUE THREAD

**Issue by PurePi** [LdB-ECM/Raspberry-Pi#9]
I'm trying to get a report from a keyboard device using this call:
```c
HIDReadReport(keyboardDevNum,
                      0,
                      (uint16_t) USB_HID_REPORT_TYPE_INPUT << 8 | 0,
                      keybReport,
                      8);
```
where keyboardDevNum is the device number of the keyboard, and keybReport is defined as `uint8_t keybReport[8] __attribute__((aligned(4)))`.
I figured out that the cause of it is that `HCDCheckErrorAndAction` is returning transmission and stall errors when called near the end of `HCDChannelTransfer`. Here's what it looks like (results ending in ..6 are ErrorTransmission, and the two at the bottom ending in ..0 are ErrorStall):
![img_20180922_163332](https://user-images.githubusercontent.com/6023821/45921963-f713d500-be85-11e8-9347-504b9eda453d.jpg)
It will consistently fail when calling `HIDReadReport` with various numbers in place of `hidIndex` and the report index of `reportValue`, yet it's successfully reading the device's product and manufacturer strings when initializing. Is `HCDCheckErrorAndAction` just falsely returning errors? I saw in issue #1 that you could read a report from the mouse. Would you mind sharing the code to do that successfully?

**Comment by LdB-ECM** [comment]
```
if ((firstMouse != 0) && (HIDReadReport(firstMouse, 0, (uint16_t)USB_HID_REPORT_TYPE_INPUT << 8 | 0, &buf[0], 4) == OK)) {
      // process the 4 byte report
}
```

It will be the same for keyboard just the keyboard ID

**Comment by PurePi** [comment]
Thank you, that worked for me. I had been testing with 2 keyboards. One of them was USB 1.1, and that's the one it wasn't able to read. It worked with a USB 2.0 keyboard though. Here's the code I used:
```c
void getKeyboardReport()
{
    uint8_t buf[8] = {0};
    uint8_t firstkbd = 0;

    for(int i = 1; i < MaximumDevices; i++)
    {
        if(IsKeyboard(i))
        {
            firstkbd = i;
            break;
        }
    }

    if(!firstkbd)
    {
        printf("Could not find keyboard\n");
        return;
    }

    printf("Keyboard found: Device #%d\n", firstkbd);
    
    RESULT status = HIDReadReport(firstkbd, 0, (uint16_t) USB_HID_REPORT_TYPE_INPUT << 8 | 0, &buf[0], 4);
    if(status == OK)
    {
        printf("Keyboard report: 0x%x\t0x%x\t0x%x\t0x%x\n", buf[0], buf[1], buf[2], buf[3]);
    }
    else
    {
        printf("HID report error: 0x%x\n", status);
    }
}
```
Note: The keyboard report is actually 8 bytes ([source](https://docs.mbed.com/docs/ble-hid/en/latest/api/md_doc_HID.html)).
And here's the output:
![img_20180924_184609](https://user-images.githubusercontent.com/6023821/45985214-cde07980-c02a-11e8-9ab2-05883a893e86.jpg)

**Comment by LdB-ECM** [comment]
I added the code to demo code and as resolved closing the issue
